### ISSUE TITLE
Python code can't be indented automatically in the IPython console while working with comint-mime.

### ISSUE THREAD

**Issue by hongyi-zhao** [astoff/comint-mime#10]
On Ubuntu 20.04.3 LTS, I installed `comint-mime` with the following configuration:

```emacs-lisp
(use-package comint-mime
  :straight ( :host github
	      :repo "astoff/comint-mime"
	      :files (:defaults "*.py" "*.sh"))
  ;;https://github.com/jwiegley/use-package#hooks
  ;;https://github.com/astoff/comint-mime#usage
  ;;https://mail.google.com/mail/u/0?ik=7b73d6af10&view=om&permmsgid=msg-a%3Ar-1233702610310931433
  ;;https://mail.google.com/mail/u/0?ik=7b73d6af10&view=om&permmsgid=msg-a%3Ar5550893479419332762
  :hook ((shell-mode inferior-python-mode) . comint-mime-setup)
  :custom
  ;;  https://emacs.stackexchange.com/a/33992
  ;;https://github.com/astoff/comint-mime/issues/4#issuecomment-938384059
  (org-format-latex-options '(plist-put org-format-latex-options :scale 1.5))
  )
```

When I type some python code in the IPython console with the major mode `inferior-python-mode` enabled, I find that the Python code can't be indented automatically, as shown below:

![image](https://user-images.githubusercontent.com/11155854/147845816-ef422069-ec3a-4263-a64b-35eeaefdefba.png)

Any hints for this problem?

Regards,
HZ

**Comment by astoff** [comment]
What you typed is not valid Python syntax. There should be some spaces you need to type before `print`.

You can also check https://github.com/jdtsmith/python-mls. But the problem is unrelated to comint-mime.

**Comment by hongyi-zhao** [comment]
> What you typed is not valid Python syntax. There should be some spaces you need to type before `print`.

I want the `print` command to indent automatically instead of typing spaces there manually.
 
> You can also check https://github.com/jdtsmith/python-mls. But the problem is unrelated to comint-mime.

Glad to know this package. It seems that it was developed to solve similar but not limited to the above problem.
