### ISSUE TITLE
Ipython console with inferior python mode can't complete many python keywords/hints. 

### ISSUE THREAD

**Issue by hongyi-zhao** [astoff/comint-mime#11]
On Ubuntu 20.04.3 LTS, I use `comint-mime` with the following configuration:

```emacs-lisp
(use-package comint-mime
  :straight ( :host github
	      :repo "astoff/comint-mime"
	      :files (:defaults "*.py" "*.sh"))
  ;;https://github.com/jwiegley/use-package#hooks
  ;;https://github.com/astoff/comint-mime#usage
  ;;https://mail.google.com/mail/u/0?ik=7b73d6af10&view=om&permmsgid=msg-a%3Ar-1233702610310931433
  ;;https://mail.google.com/mail/u/0?ik=7b73d6af10&view=om&permmsgid=msg-a%3Ar5550893479419332762
  :hook ((shell-mode inferior-python-mode) . comint-mime-setup)
  :custom
  ;;  https://emacs.stackexchange.com/a/33992
  ;;https://github.com/astoff/comint-mime/issues/4#issuecomment-938384059
  (org-format-latex-options '(plist-put org-format-latex-options :scale 1.5))
  )
```

But I find that ipython console with inferior python mode can't complete many python keywords/hints.  See the following for detailed information:

![image](https://user-images.githubusercontent.com/11155854/148338804-71d17c2c-a887-40ae-9c32-883ddc580534.png)

In the normal python mode, the completion will be shown as follows:

![image](https://user-images.githubusercontent.com/11155854/148339400-0487fc86-9c80-4590-9dff-d669e69a2e4c.png)

Any hints for this problem?

Regards,
HZ

**Comment by astoff** [comment]
Since this seems unrelated to comint-mime I'll close the issue.
