### ISSUE TITLE
comint-mime in MS Windows emacs

### ISSUE THREAD

**Issue by chlee1126** [astoff/comint-mime#15]
It works when line 99 of comint-mime.el is changed: (url-filename url) --> (url-host url)

**Comment by astoff** [comment]
What is the value of the `file` variable in both cases? (You can try e.g. adding `(message "=> %s" file)` to line 101.)

**Comment by chlee1126** [comment]
1)
.....
(let* ((tmp (match-beginning 1))				          
                          (url (url-generic-parse-url payload))
                          (file (concat (file-remote-p default-directory)
                          (url-filename url))))
                     (with-temp-buffer
					   (message "=>%s" file)
                                           (set-buffer-multibyte nil)
.....
=>
2)
.....
(let* ((tmp (match-beginning 1))				          
                          (url (url-generic-parse-url payload))
                          (file (concat (file-remote-p default-directory)
                          (url-host url))))
                     (with-temp-buffer
					   (message "=>%s" file)
                                           (set-buffer-multibyte nil)
.....
=>c:\users\user\appdata\local\temp\tmpa533hli4

O/S: windows 10
gnu emacs: 28.1

**Comment by chlee1126** [comment]
I checked some other variables as below:
_=>5151
text=>{"type": "image/png"}
tmpfile://C:\Users\user\AppData\Local\Temp\tmpc5dpr6c8
paylod=>tmpfile://C:\Users\user\AppData\Local\Temp\tmpc5dpr6c8
url=>#s(url tmpfile nil nil c:\users\user\appdata\local\temp\tmpc5dpr6c8 nil  nil nil t nil t t)

**Comment by astoff** [comment]
Thanks for the info!

Can you check that the version in the [fix-windows-uri](https://github.com/astoff/comint-mime/tree/fix-windows-uri) branch works?  You can just dump the new version of comint-mime.py into wherever Emacs originally installed this file for you.

**Comment by chlee1126** [comment]
I overwrited comint-mime.py from fix-windows-uri. but It didn't work.
And I checked the variables were as below:
    _=>5151
    text =>{"type": "image/png"}
    tmpfile:///C:/Users/user/AppData/Local/Temp/tmpz8nk9t7x
    payload=>tmpfile:///C:/Users/user/AppData/Local/Temp/tmpz8nk9t7x
    url=>#s(url tmpfile nil nil  nil /C:/Users/user/AppData/Local/Temp/tmpz8nk9t7x nil nil t nil t t)
    file=>/C:/Users/user/AppData/Local/Temp/tmpz8nk9t7x

I found file variable started with  "/".  
So I temporarily forced to remove first "/"  character using substring function in comint-mime.el as below:

(let* ((tmp (match-beginning 1))
                          (url (url-generic-parse-url payload))
                          (file (concat (file-remote-p default-directory)
                                        (url-filename url)))
						   (file (substring file 1)))

After that, I found It worked properly.

**Comment by astoff** [comment]
Thanks. The change you mentioned of course only works on Windows, so let me see how to do this in a way that works on any OS.

**Comment by astoff** [comment]
Okay, this should be fixed in the main branch (but not yet in the released ELPA version). It would be great if you could do a quick test, since I don't have access to a Windows machine.
