### ISSUE TITLE
how to debug?

### ISSUE THREAD

**Issue by cremacs1** [astoff/comint-mime#16]
Hi,

I'm trying to use your package with spacemacs, but installing the package and activating it via `comint-mime-setup` in the REPL doesn't seem to have any effect. I also tried adding hooks as in your readme. It does work perfectly in `emacs -q` (after installing the package). 

Do you have any suggestions about how to debug this? So far I've tried to debug by checking that `comint-mime-setup` has the desired effect; I checked that `comint-osc-handlers` contains `("5151" . comint-mime-osc-handler)` and that  `comint-output-filter-functions` contains `comint-osc-process-output`. These look fine. But I'm not sure what to look at next.

Thanks!

**Comment by astoff** [comment]
Sorry for the delay to reply, I suppose this is out-of-date by now so I will close the issue.
