### ISSUE TITLE
realpath on Mac does not accept -e flag

### ISSUE THREAD

**Issue by sje30** [astoff/comint-mime#17]
In the comint-mime.sh script, line 22:

        file=$(realpath -e "$1") || return 1

the -e flag on linux indicates that 'all components of the path must exist'

This -e flag doesn't exist on Mac  version of realpath in /bin.  Instead realpath will error if the file does not exist.  So on Mac, the -e flag can be deleted to have the same effect as realpath on linux (it seems).

**Comment by astoff** [comment]
Thanks for letting me know!
