### ISSUE TITLE
Possible to set width/size of image?

### ISSUE THREAD

**Issue by swflint** [astoff/comint-mime#18]
Is there a way to set the width/size of the image?  Relative to the size of the window?

**Comment by astoff** [comment]
Currently there's nothing this package can do directly. You can, with point over the image, type `i C-h` etc to see some available option (or maybe on some older Emacs, type `+` or `-` with point over the image). Also, if the image is coming from matplotlib, probably the best option is to modify the matplotlib settings.

Which image specifically you would like to adjust?

**Comment by swflint** [comment]
I'll have to play around with how to do it for SVG images, but I think for regular images, providing a way to set default properties (initially none?) should be sufficient.

I'll PR shortly.
