### ISSUE TITLE
user-error: ‘comint-mime’ only makes sense in comint buffers

### ISSUE THREAD

**Issue by hongyi-zhao** [astoff/comint-mime#2]
I tried with the following example:
```python
import matplotlib.pyplot as plt
from numpy import arange, sin, pi
t = arange(0, 2*pi, 0.01)
plt.plot(sin(4*t), sin(5*t))
```
The corresponding Emacs configuration:

```emacs-lisp
(use-package comint-mime
  :straight (:host github :type git :repo "astoff/comint-mime"
             :files (:defaults "*.py" "*.sh"))
  :after elpy
  ;https://github.com/jwiegley/use-package#hooks
  ;https://github.com/astoff/comint-mime#usage
  ;https://mail.google.com/mail/u/0?ik=7b73d6af10&view=om&permmsgid=msg-a%3Ar-1233702610310931433
  ;https://mail.google.com/mail/u/0?ik=7b73d6af10&view=om&permmsgid=msg-a%3Ar5550893479419332762
  :hook (
        ((shell-mode inferior-python-mode python-mode) . comint-mime-setup)
        )
  :config
  (when (executable-find "ipython3")
    (setq python-shell-interpreter "ipython3"
          ;python-shell-interpreter-args "--simple-prompt --classic"
          ;https://elpy.readthedocs.io/en/latest/ide.html#interpreter-setup
          python-shell-interpreter-args "-i --simple-prompt --classic --pprint")))
```

When I run the python code, I meet the following error:

```
File mode specification error: (user-error ‘comint-mime’ only makes sense in comint buffers)
blank line at end of file [W391] [2 times]
Sent: import matplotlib.pyplot as plt...
Shell native completion is enabled.
Can’t guess python-indent-offset, using defaults: 4
user-error: ‘comint-mime’ only makes sense in comint buffers
```
Any hints for this problem?

Regards,
HZ

**Comment by astoff** [comment]
comint-mime only makes sense in comint buffers, and you added it to `python-mode-hook` :-)

**Comment by hongyi-zhao** [comment]
Then how to reproduce the example shown [here](https://user-images.githubusercontent.com/6500902/133823411-ca75122d-4a39-4e3c-ac55-b2a1f974ff5e.png)? I tried by both `M-x eshell` and `M-x term`, and then run the corresponding python codes with `ipython` and `python`, but none of them shown the plot in Emacs' frame: 

![image](https://user-images.githubusercontent.com/11155854/133923839-8733a73c-a371-409e-9dc5-d635a2e7c47f.png)

**Comment by astoff** [comment]
You need the good old Python shell, `M-x run-python`.

**Comment by hongyi-zhao** [comment]
Still failed to do the trick by the following steps:

```emacs-lisp
M-x run-python RET
M-x comint-mime-setup RET
```
Then input the python codes as following:

![image](https://user-images.githubusercontent.com/11155854/133924540-df4ca9e7-823b-47c8-bc2b-209d48b7f23b.png)

**Comment by astoff** [comment]
Are you using Emacs 28, with a freshly compiled master branch?

**Comment by hongyi-zhao** [comment]
I use the self compiled git master version: 
`GNU Emacs 28.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.20, cairo version 1.16.0) of 2021-09-09`

**Comment by astoff** [comment]
Does the other example of the screenshot (with LaTeX output) work? I've found the Matplotlib part of the setup to be finicky. Sometimes typing `%matplotlib inline` in the shell helps. Otherwise, let me know if you figure this out, because I'm not sure either.

**Comment by hongyi-zhao** [comment]
With the method suggested [here](https://stackoverflow.com/questions/19410042/how-to-make-ipython-notebook-matplotlib-plot-inline):
```
$ cat ~/.ipython/profile_default/ipython_config.py
c.InteractiveShellApp.matplotlib = 'inline'
```
The matplotlib can display inline plots now, for both `python-mode` and `inferior-python-mode`, but LaTeX output still fails:
![image](https://user-images.githubusercontent.com/11155854/133926626-7072fdba-7a71-40f1-bcff-1cdc7204975f.png)
