### ISSUE TITLE
Adaptations are needed for MacOS

### ISSUE THREAD

**Issue by guibor** [astoff/comint-mime#3]
A few small adaptations:
- might be worth indicating in the instructions that coreutils need to be installed
- probably need to use "file -bI" instead of "file -bi" (in shell mode)
- the format of file types is not exactly the same as in Linux
- my current installed version of Emacs is 28.0.50 (I think that's what you get, at least if you install through brew), might be worth considering making that the minimum version rather than 28.1

**Comment by astoff** [comment]
>  might be worth indicating in the instructions that coreutils need to be installed

What exactly requires coreutils, and is there an easy replacement?

>  probably need to use "file -bI" instead of "file -bi" (in shell mode)

This is the output I expect:

```
$ file -bi kitty.jpg 
image/jpeg; charset=binary
```

Is this what `file -bl` does on a Mac?

> the format of file types is not exactly the same as in Linux

MIME types are standardized as far as I know... There has to be a command on MacOS to print them.

> my current installed version of Emacs is 28.0.50 (I think that's what you get, at least if you install through brew), might be worth considering making that the minimum version rather than 28.1

Done.
