### ISSUE TITLE
Customize the displayed font family and font size for the ipython output in comint buffer.

### ISSUE THREAD

**Issue by hongyi-zhao** [astoff/comint-mime#4]
Currently, I'm using the `comint-mime` package with the following configuration:

```emacs-lisp
(use-package comint-mime
  :straight (:host github :repo "astoff/comint-mime"
             :files (:defaults "*.py" "*.sh"))
  :hook ((shell-mode inferior-python-mode) . comint-mime-setup))
```

With the help of this package, I can display python matplotlib plot and sympy formulae in Emacs comint buffer, as shown in the screenshot below:

![image](https://user-images.githubusercontent.com/11155854/136482962-d4b56831-666d-4da0-9c6e-568635b5038f.png)

But I want to know if I can customize the displayed font family and font size for the ipython output in comint buffer.

Any hints will be appreciated.

Regards, HZ

**Comment by astoff** [comment]
For the LaTeX conversion, see `org-format-latex-options` (you could have discovered this by looking at the code to see which function handles LaTeX stuff).

As to the plot, they are just images, you can't do anything on the Emacs side. If you're making these images with Matplolib, then look up its documentation to see how to customize things.
