### ISSUE TITLE
Symbol’s value as variable is void: comint-osc-handlers

### ISSUE THREAD

**Issue by andreas-roehler** [astoff/comint-mime#5]
Thanks delivering that interesting package. 

For now, when calling M-x comint-mime-setup RET in a shell-buffer, get the error
"Symbol’s value as variable is void: comint-osc-handlers"

**Comment by astoff** [comment]
I'm guessing you are not on Emacs 28? This package needs a new feature in comint.el (OSC escape sequences).

**Comment by astoff** [comment]
Yes, the OSC feature in comint.el is rather recent, from the end of August. So the package should work once you pull the master or emacs-28 branch and recompile.
