### ISSUE TITLE
Running from python-mode.el

### ISSUE THREAD

**Issue by andreas-roehler** [astoff/comint-mime#6]
Hi, 
great package. Running from python-mode.el needs a minor tweak. Should deliver a patch. For the moment a picture from a working example. BTW output appears as a separate window here, which should not be an issue
![python-mode-el](https://user-images.githubusercontent.com/1173139/137110732-68bdeaaf-504f-46bb-894a-97ac407bfae4.png)
.

**Comment by astoff** [comment]
In fact, this this shows that comint-mime didn't kick in, as one would expect.

If you are interested in adding support for python-mode.el, I would need a function similar to this (which is python.el-specific):

https://github.com/astoff/comint-mime/blob/2ac67834d9bb8e6a3521d75b934a4b496a3a0f9d/comint-mime.el#L198-L211

**Comment by andreas-roehler** [comment]
Thanks, will into it.

Am 06.04.22 um 09:16 schrieb Augusto Stoffel:
